### ISSUE TITLE
Crash on start WinXP

### ISSUE THREAD

**Issue by Sintendo** [Themaister/RetroArch-Phoenix#13]
Latest retroarch-phoenix.exe included with retroarch-win32-0.9.9.zip crashes immediately on launch on Windows XP. Windows 7 64-bit seems to have no issues running both win32 and win64 version. The 0.9.9-wip3 version worked fine too.

**Comment by Themaister** [comment]
I cannot test on XP, and it works in Wine, so I cannot reproduce the issue. I need a full backtrace from gdb.

**Comment by Sintendo** [comment]
I was going to try and to get you a backtrace, but the build I just compiled from latest git won't crash...

**Comment by Themaister** [comment]
Between wip3 and 0.9.9 I got a new HDD and rebuilt MinGW-w64 cross chain (didn't change source of Phoenix I think?). Could be something about the compiler.

**Comment by Sintendo** [comment]
I used this one: http://sourceforge.net/projects/mingwbuilds/files/host-windows/releases/4.8.1/32-bit/threads-posix/dwarf/

**Comment by ekipan** [comment]
Likewise, on Windows XP 32-bit, the official RetroArch Phoenix 0.9.9 crashed for me but the one I built goes without issue. Could I ask you to upload a debug build or symbol table so I can give you a useful backtrace? Here's what I got without symbols:

```
(gdb) r
Starting program: C:\Documents and Settings\Nick\My Documents\emu\retroarch-0.9.9\retroarch-phoenix.exe
[New Thread 3800.0xdfc]
[New Thread 3800.0xe78]
[New Thread 3800.0xd34]

Program received signal SIGSEGV, Segmentation fault.
0x00404d36 in ?? ()
(gdb) bt
#0  0x00404d36 in ?? ()
#1  0x7e418816 in USER32!GetDC () from C:\WINDOWS\system32\user32.dll
#2  0x0040e3c0 in ?? ()
#3  0x7e428ea0 in USER32!DefWindowProcW () from C:\WINDOWS\system32\user32.dll
#4  0x00000000 in ?? ()
```

At the time of the segfault, a window is visible, without any contents. http://i.imgur.com/Dz7d6iV.png
